# -*- coding: utf-8 -*-
"""final year project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPGCmLE3E9LDdFDP165iJVXJNUaxIjju
"""

!nvidia-smi

!pip install ultralytics

# from IPython import display
# display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# !pip install roboflow

# from roboflow import Roboflow
# rf = Roboflow(api_key="ktqrEfx5nd7CMRBpmvwY")
# project = rf.workspace("vibhore").project("swachmukhh")
# version = project.version(2)
# dataset = version.download("yolov8")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ktqrEfx5nd7CMRBpmvwY")
project = rf.workspace("vibhore").project("grocery_items-7i2em-qifvn")
version = project.version(1)
dataset = version.download("yolov8")

# !yolo task=detect mode=train model=yolov8s.pt data=/content/data.yaml epochs=25 imgsz=800 plots=True

!yolo task=detect mode=train model=yolov8s.pt data=/content/Grocery_Items-1/data.yaml epochs=10 imgsz=800 plots=True

from IPython.display import display, Image
Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

# !yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data=/content/data.yaml

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data=/content/swachMukhh-2/data.yaml

# !yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source=/content/test/images save=True

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source=/content/swachMukhh-2/test/images save=True

# prompt: download runs folder

!zip -r /content/runs.zip /content/runs
from google.colab import files
files.download("/content/runs.zip")

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/detect/predict3/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")

!zip -r /content/runs.zip /content/runs
from google.colab import files
files.download("/content/runs.zip")

!pip install roboflow --quiet

from roboflow import Roboflow
rf = Roboflow(api_key="YOUR_API_KEY")
project = rf.workspace("roboflow-jvuqo").project("football-players-detection-3zvbc")
dataset = project.version(1).download("yolov8")

from roboflow import Roboflow
rf = Roboflow(api_key="ktqrEfx5nd7CMRBpmvwY")
project = rf.workspace("vibhore").project("swachmukhh")
version = project.version(1)
dataset = version.download("yolov8")

project.version(dataset.version).deploy(model_type="yolov8", model_path=f"/content/runs/detect/train/")



